# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	increment_build_number
    cert
    sigh

    gym(
      #clean: true,	
      configuration: "Debug",
      scheme: "BGLMedia",
      buildlog_path: 'fastlane/logs'
    )

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
     pilot(
      skip_submission: true,
      distribute_external: false
      #,
      #skip_waiting_for_build_processing: true
    )
  end
end
